const fs = require('fs');
const path = require('path');

const obsidianDir = path.join(__dirname, 'obsidian');
const jsonOutputFile = path.join(obsidianDir, 'tree.json');
const jsOutputFile = path.join(obsidianDir, 'tree_data.js');

function buildTree(dir, relativePath = '') {
    if (!fs.existsSync(dir)) return [];
    const items = fs.readdirSync(dir, { withFileTypes: true });
    const result = [];
    
    // Sort directories and html files separately
    const dirs = items.filter(i => i.isDirectory());
    const files = items.filter(i => i.isFile() && i.name.endsWith('.html'));

    dirs.sort((a, b) => a.name.localeCompare(b.name, 'ko'));
    files.sort((a, b) => a.name.localeCompare(b.name, 'ko'));

    for (const d of dirs) {
        const subRel = relativePath ? `${relativePath}/${d.name}` : d.name;
        const children = buildTree(path.join(dir, d.name), subRel);
        if (children.length > 0) {
            result.push({
                name: d.name,
                type: 'directory',
                path: subRel,
                children: children
            });
        }
    }

    for (const f of files) {
        const subRel = relativePath ? `${relativePath}/${f.name}` : f.name;
        const nameWithoutExt = path.basename(f.name, '.html');
        result.push({
            name: nameWithoutExt,
            type: 'file',
            path: subRel
        });
    }

    return result;
}

console.log('Scanning obsidian folder to build directory tree...');
const treeData = buildTree(obsidianDir);

fs.writeFileSync(jsonOutputFile, JSON.stringify(treeData, null, 2), 'utf-8');
console.log(`Saved JSON tree to ${jsonOutputFile}`);

const jsContent = `// Auto-generated by update_tree.js\nwindow.OBSIDIAN_TREE_DATA = ${JSON.stringify(treeData, null, 2)};\n`;
fs.writeFileSync(jsOutputFile, jsContent, 'utf-8');
console.log(`Saved JS tree to ${jsOutputFile}`);
